# Generated by Django 2.0 on 2017-12-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurace', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servedin',
            new_name='DishInRestaurant',
        ),
    ]
